apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pimclaw-pvc-test-2
  namespace: baota-playground
  labels:
    app: pimclaw-new
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nexdata-block
  volumeMode: Filesystem
