apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pimclaw-pvc-test-1
  namespace: baota-playground
  labels:
    app: pimclaw
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nexdata-block
  volumeMode: Filesystem
